FROM base/archlinux:latest
MAINTAINER Mathieu Tarral <mathieu.tarral@gmail.com>

# Install dependencies
#---------------------------
# -> Essentials
RUN pacman --noconfirm -Syu && \
    pacman-db-upgrade && \
    pacman --noconfirm -Sy gcc git cmake make vim doxygen bzr && \
    pacman --noconfirm -Sy perl perl-json perl-libwww perl-xml-parser dialog \
                            qt5-base && \
    pacman --noconfirm -Sy \
                                libpwquality \
                                xf86-input-synaptics xorg-server-devel \
                                gtkmm gtkmm3 \
                                xapian-core \
                                libepoxy \
                                libmm-glib \
                                fontforge \
                                qt5-quick1 \
                                exiv2 \
                                sane && \
    pacman --noconfirm -Sy \
                                qt5-script \
                                qt5-x11extras \
                                docbook-xsl \
                                qt5-tools \
                                qt5-svg boost \
                                giflib \
                                vlc \
                                pkg-config \
                                libnm-glib && \
    pacman --noconfirm -Sy \
                                grantlee-qt5 \
                                glu \
                                automoc4 \
                                qt5-multimedia \
                                eigen && \
    useradd -d /home/kdedev -m kdedev && \
    mkdir /work /tmp/kdesrc-build /qt && \
    chown kdedev /work /tmp/kdesrc-build /qt

#^^ kdedev user is added. It will use UID=1000 for files created in volumes ^^

# -> KDE Frameworks 5
# KF5 COMPONENT         |       BUILD DEPENDENCY
#-----------------------|--------------------------
# ki18n                 |       qt5-script
# kwindowsystem         |       qt5-x11extras
# kdocbook              |       docbook-xsl
# kwidgetsaddons        |       qt5-tools
# kiconthemes           |       qt5-svg
# kactivities           |       boost
# khtml                 |       giflib
# phonon-vlc            |       vlc
# phonon-gstreamer      |       pkg-config
# networkmanager-qt     |       libnm-glib
#-----------------------------------------------
# Alternatively, you can install binary packages for kf5 from arch repositories :
# RUN pacman --noconfirm -S kf5
# -> KDE Workspace
# KDE WORKSPACE COMP    |       BUILD DEPENDENCY
#-----------------------|----------------------------
# user-manager          |       libpwquality
# kcm-touchpad          |       xf86-input-synaptics xorg-server-devel
# kde-gtk-config        |       gtkmm gtkmm3
# baloo                 |       xapian-core
# kwin                  |       libepoxy
# libnm-qt              |       libmm-glib
# oxygen-fonts          |       fontforge
# kdevplatform          |       qt5-quick1
# gwenview              |       exiv2
# libksane              |       sane
# -> KDE Appliations
# KDE WORKSPACE COMP    |       BUILD DEPENDENCY
#-----------------------|----------------------------
# kdevplatform          |       grantlee-qt5
# kalgebra              |       glu
# marble                |       automoc4
# parley                |       qt5-multimedia
# step                  |       eigen

COPY kdesrc-buildrc /home/kdedev/.kdesrc-buildrc
COPY bashrc /home/kdedev/.bashrc
RUN chown kdedev /home/kdedev/.kdesrc-buildrc /home/kdedev/.bashrc
USER kdedev
ENV HOME /home/kdedev
WORKDIR /home/kdedev/
# kde anongit url alias
RUN git config --global url."git://anongit.kde.org/".insteadOf kde: && \
    git config --global url."ssh://git@git.kde.org/".pushInsteadOf kde: && \
    git clone git://anongit.kde.org/kdesrc-build.git 

VOLUME /work
VOLUME /qt

ENTRYPOINT ["/bin/bash"]
