FROM base/archlinux:latest
MAINTAINER Mathieu Tarral <mathieu.tarral@gmail.com>

RUN pacman --noconfirm -Syu

# add simple user
#------------------
RUN useradd -m docker
RUN pacman-db-upgrade
RUN pacman --noconfirm -S sudo
RUN echo "docker ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Install dependencies
#---------------------------
# -> Essentials
RUN pacman --noconfirm -S gcc git cmake make vim doxygen bzr
# -> kdesrc-build script
RUN pacman --noconfirm -S perl perl-json perl-libwww perl-xml-parser dialog \
                            qt5-base # qmake
# -> KDE Frameworks 5
# KF5 COMPONENT         |       BUILD DEPENDENCY
#-----------------------|--------------------------
# ki18n                 |       qt5-script
# kwindowsystem         |       qt5-x11extras
# kdocbook              |       docbook-xsl
# kwidgetsaddons        |       qt5-tools
# kiconthemes           |       qt5-svg
# kactivities           |       boost
# khtml                 |       giflib
# phonon-vlc            |       vlc
# phonon-gstreamer      |       pkg-config
#-----------------------------------------------
# Alternatively, you can install binary packages for kf5 from arch repositories :
# RUN pacman --noconfirm -S kf5
RUN pacman --noconfirm -S qt5-script qt5-x11extras docbook-xsl qt5-tools \
                            qt5-svg boost giflib vlc pkg-config
# -> KDE Workspace
# KDE WORKSPACE COMP    |       BUILD DEPENDENCY
#-----------------------|----------------------------
# user-manager          |       libpwquality
# kcm-touchpad          |       xf86-input-synaptics
# kde-gtk-config        |       gtkmm gtkmm3
# baloo                 |       xapian-core
# kwin                  |       libepoxy
# libnm-qt              |       libmm-glib
# libbluedevil          |
# plasmate              |
# oxygen-fonts          |       fontforge
# kdevplatform          |       qt5-quick1
# gwenview              |       exiv2
# libksane              |       sane
RUN pacman --noconfirm -S libpwquality xf86-input-synaptics gtkmm gtkmm3 \
                            xapian-core libepoxy libmm-glib fontforge \
                            qt5-quick1 exiv2 sane

# kde anongit url alias
RUN su docker -c 'git config --global url."git://anongit.kde.org/".insteadOf kde:'

VOLUME /work
RUN chown docker:docker /work
WORKDIR /work
ENTRYPOINT ["/bin/bash"]
