FROM fedora:latest
MAINTAINER Mathieu Tarral <mathieu.tarral@gmail.com>

RUN yum -y upgrade

# add simple user
#------------------
RUN useradd -m docker
RUN yum -y install sudo
RUN echo "docker ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# install some dev tools
#-------------
RUN yum -y install git vim tree

# kdesrc-build requirements
#---------------------------
RUN yum -y install gcc-c++ cmake bzr doxygen
RUN yum -y install dialog perl-libwww-perl perl-JSON perl-XML-Parser gettext docbook-style-xsl xcb-util-keysyms-devel libxslt-devel libxml2-devel libXrender-devel libgudev1-devel
RUN yum -y install qt-develop qt-config
# install Qt5 development packages
RUN yum -y install qt5-qtbase-devel qt5-qtxmlpatterns-devel qt5-qtx11extras-devel qt5-qttools-devel qt5-qtsvg-devel qt5-qtscript-devel qt5-qttools-static
# kde anongit url alias
RUN su docker -c 'git config --global url."git://anongit.kde.org/".insteadOf kde:'

VOLUME /work
RUN chown docker:users /work
WORKDIR /work
ENTRYPOINT ["sudo -u docker /bin/bash"]
