FROM opensuse:13.2
MAINTAINER Mathieu Tarral <mathieu.tarral@gmail.com>

# add Qt5 repo
#---------------
RUN zypper -n --gpg-auto-import-keys refresh
RUN zypper ar -f "http://download.opensuse.org/repositories/KDE:/Qt5/openSUSE_13.2/" "Qt5"
RUN zypper --non-interactive --gpg-auto-import-keys refresh

# Install dependencies
#---------------------------
# -> Essentials
RUN zypper --non-interactive in vim tar git bzr cmake doxygen
# -> kdesrc-build script
RUN zypper --non-interactive in perl-libwww-perl perl-XML-Parser perl-JSON \
                                    dialog python ca-certificates libqt4-devel # qmake
# -> KDE Frameworks 5
# KF5 COMPONENT         |     BUILD DEPENDENCY
#-----------------------|------------------------
# libdbusmenu-qt        |       libQt5DBus-devel
# attica                |       libQt5Test-devel
# ki18n                 |       gettext-tools libQt5Concurrent-devel
# kwindowsystem         |       libqt5-x11extras-devel xcb-util-keysyms-devel
# kdoctools             |       libxslt-devel docbook-xsl-stylesheets
# kwidgetsaddons        |       libqt5-qttools-devel
# kxml-gui              |       libQt5PrintSupport-devel
# kiconthemes           |       libqt5-qtsvg-devel
# kdeclarative          |       libqt5-qtquick1-devel libepoxy-devel
# kactivities           |       boost-devel
# solid                 |       libgudev-1_0-devel
# kdewebkit             |       libQt5WebkKit5-devel libQt5WebKitWidgets-devel
# khtml                 |       giflib-devel
# frameworkintegration  |       libqt5-qtbase-private-headers-devel
# ktexteditor           |       libqt5-qtxmlpatters-devel
# polkit-qt-1           |       libpolkit-qt-1-devel
# phonon-vlc            |       vlc-devel
# phonon-gstreamer      |       libQt5OpenGL-devel gstreamer-editing-services-devel
# networkmanager-qt     |       NetworkManager-devel
#-----------------------------------------------
RUN zypper --non-interactive in \
        libQt5DBus-devel \
        libQt5Test-devel \
        gettext-tools libQt5Concurrent-devel \
        libqt5-qtx11extras-devel xcb-util-keysyms-devel \
        libxslt-devel docbook-xsl-stylesheets \
        libqt5-qttools-devel \
        libQt5PrintSupport-devel \
        libqt5-qtsvg-devel \
        libqt5-qtquick1-devel libepoxy-devel \
        boost-devel \
        libgudev-1_0-devel \
        libQt5WebKit5-devel libQt5WebKitWidgets-devel \
        giflib-devel \
        libqt5-qtbase-private-headers-devel \
        libqt5-qtxmlpatterns-devel \
        libpolkit-qt-1-devel \
        vlc-devel \
        libQt5OpenGL-devel gstreamer-editing-services-devel \
        NetworkManager-devel


# -> KDE Workspace
# KF5 COMPONENT         |       BUILD DEPENDENCY
#-----------------------|------------------------
# user-manager          |       libpwquality-devel
# libmm-qt              |       ModemManager-devel
# kde-gtk-config        |       gtk2-devel gtk3-devel
# kfilemetadata         |       libattr-devel
# oxygen-fonts          |       fontforge-devel
# kwayland              |       wayland-devel
# kwin                  |       xcb-util-image-devel
# kcm-touchpad          |       xf86-input-synaptics-devel xorg-server xorg-x11-util-devel libX11-devel  libxkbcommon-x11-devel
# baloo                 |       libxapian-devel
#-----------------------------------------------
RUN zypper --non-interactive in \
        libpwquality-devel \
        ModemManager-devel \
        gtk2-devel gtk3-devel \
        libattr-devel \
        fontforge-devel \
        wayland-devel \
        xcb-util-image-devel \
        xf86-input-synaptics-devel xorg-x11-devel xorg-x11-util-devel libX11-devel libxkbcommon-x11-devel \
        libxapian-devel

# -> KDE Applications
# KF5 COMPONENT         |       BUILD DEPENDENCY
#-----------------------|------------------------
# kdevplatform          |       grantlee5-devel
# gwenview              |       libexiv2-devel
# lokalize              |       hunspell-devel
# libksane              |       sane-backends-devel
# kalgebra              |       glu-devel
# marble                |       automoc4
# parley                |       libqt5-qtmultimedia-devel
# step                  |       eigen3-devel
# kcalc                 |       gmp-devel
# print-manager         |       cups-devel
# ark                   |       libarchive-devel
# kmix                  |       alsa-devel
# libkdegames           |       libsndfile-devel openal-soft-devel
# ksirk                 |       libqca-qt5-devel
#-----------------------------------------------
RUN zypper --non-interactive in \
                              grantlee5-devel \
                              libexiv2-devel \
                              hunspell-devel \
                              sane-backends-devel \
                              glu-devel \
                              automoc4 \
                              libqt5-qtmultimedia-devel \
                              eigen3-devel \
                              gmp-devel \
                              cups-devel \
                              libarchive-devel \
                              alsa-devel \
                              libsndfile-devel openal-soft-devel \
                              libqca-qt5-devel

# -> KDE PIM
# KDE WORKSPACE COMP    |       BUILD DEPENDENCY
#-----------------------|----------------------------
# prison                |       libdmtx-devel qrencode-devel
# kcalcore              |       libical-devel
# kimap                 |       cyrus-sasl-devel
# kldap                 |       openldap2-devel
# gpgmepp               |       libgpgme-devel
#-----------------------------------------------
RUN zypper --non-interactive in \
                                libdmtx-devel qrencode-devel \
                                libical-devel \
                                cyrus-sasl-devel \
                                openldap2-devel \
                                libgpgme-devel


# kde anongit url alias
RUN git config --global url."git://anongit.kde.org/".insteadOf kde:

VOLUME /work
WORKDIR /work
ENTRYPOINT ["/bin/bash"]
